Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/config/routes.rb
SmalrubyEditor::Application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    root to: 'editor#index'
  end

  match '/demo(/:filename)' => 'editor#demo',
        defaults: { filename: 'car_chase' }, via: :get

  resources :sessions, only: [:create, :destroy]
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :source_codes, only: [:create, :index]
  post 'source_codes/check'
  delete 'source_codes/download'
  post 'source_codes/load'
  post 'source_codes/load_local'
  post 'source_codes/load_demo'
  delete 'source_codes/write'
  post 'source_codes/run'
  post 'source_codes/to_blocks'

end

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/controllers/editor_controller.rb
# -*- coding: utf-8 -*-
class EditorController < ApplicationController
  def index
  end

  def demo
    @filename = (File.basename(params[:filename]) || 'car_chase') + '.rb.xml'
  end
end

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/views/editor/_block_tab.html.haml
#block-tab-right-pane{:class => 'right-pane'}
  #blockly-div

  = render "toolbox_#{toolbox_name}"

#block-tab-left-pane{:class => 'left-pane'}
  #selectors-container
    %ul.nav{:class => 'nav-pills'}
      %li.active
        %a{:href => '#character-selector-tab', :'data-toggle' => 'tab'}<
          = t('.character')
      -#%li
        -#%a{:href => '#scene-selector-tab', :'data-toggle' => 'tab'}<
          -#= t('.stage')

    #selectors-tab-content{:class => 'tab-content'}
      #character-selector-tab{:class => 'tab-pane active selector-tab'}
        #character-selector-character-set
        - if !SmalrubyEditor::Config.enabled?('disabled_new_character')
          .item
            %a#add-character-button{:class => 'character'}
              %i.icon-plus-sign-alt
              %br
              = t('.new_character')

      #scene-selector-tab{:class => 'tab-pane selector-tab'}
        .item
          %a{:href => '#', :onclick => 'window.event.preventDefault();'}
            %div
        .item
          %a{:href => '#', :onclick => 'window.event.preventDefault();'}
            %div

= render 'character_modal'

%script#character-selector-template{:type => 'text/template'}
  .item
    .item-info
      .name
        {{- get('name') }}
      .attributes
        X: {{- get('x') }} Y: {{- get('y') }}
        %br
        = t('.direction_parameter')
        %i{class: "{{- rotationStyleIconName() }}"}
        {{- get('angle') }}°

      %a.add-block-button
        %i.icon-folder-close-alt
        %i.icon-double-angle-right

      %a.remove-button
        %i.icon-remove

    %a.character
      %img{:src => '{{- costumeUrl() }}'}

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/views/editor/_load_modal.html.haml
#load-modal{:class => "#{modal_css_class}", :tabindex => "-1",
            :role => "dialog", :"aria-hidden" => "true"}
  .modal-body
    %ul.thumbnails{:id => "load-modal-local-programs",
                   :class => "list-programs"}

    .page-header
      %h3<
        %i.icon-th-large
        = t('.preset_programs')
    %ul.thumbnails{:id => "load-modal-demo-programs",
                   :class => "list-programs"}

    .page-header
      %h3<
        %i.icon-search
        = t('.find_program')
    %ul.thumbnails{:class => "list-programs"}
      %li
        %a#load-modal-find-from-computer.thumbnail
          %h1.icon
            %i.icon-folder-open-alt
          %blockquote
            %p
              = t('.computer')
            %small
              Computer

  .modal-footer
    .pull-left
      %button#load-modal-remix-button.btn<
        %i.icon-refresh
        = t('.remix')
    %button.btn{:"data-dismiss" => "modal", :"aria-hidden" => "true"}<
      %i.icon-remove
      = t('common.cancel')
    %button#load-modal-ok-button{:class => "btn btn-primary"}<
      %i.icon-circle-blank
      = t('common.ok')

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/views/editor/_signin_modal.html.haml
#signin-modal{class: "#{modal_css_class}", tabindex: "-1",
              role: "dialog", :"aria-hidden" => "true"}
  .modal-body
    %h4
      %i.icon-info-sign
      = raw(t('.message'))
    %form#signin-modal-form.form-horizontal
      .control-group{for: "username"}
        %label.control-label{for: "signin-modal-username"}<
          = t('common.name')
        .controls
          %input#signin-modal-username.input-large{name: "username", type: "text", placeholder: t('.username_placeholder')}

  .modal-footer
    - if !SmalrubyEditor::Config.enabled?('must_signin')
      %button#signin-modal-cancel-button.cancel-button{class: "btn", :"data-dismiss" => "modal", :"aria-hidden" => "true"}<
        %i.icon-remove
        = t('common.cancel')
    %button#signin-modal-ok-button.ok-button{class: "btn btn-primary"}<
      %i.icon-circle-blank
      = t('common.login')

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/views/editor/_toolbox_raspberrypi.html.haml
%xml{:id => 'toolbox', :style => 'display: none'}
  - category = 'motion'
  %category{:name => tt('.motion')}
    -# (　)歩動かす
    %block{:type => "#{category}_move"}
      = toolbox_number_value('STEP', 10)

    -# 時計回りに(　)度回す
    %block{:type => "#{category}_rotate_right"}
      = toolbox_number_value('ANGLE', 15)

    -# 反時計回りに(　)度回す
    %block{:type => "#{category}_rotate_left"}
      = toolbox_number_value('ANGLE', 15)

    -# (　)度に向ける
    %block{:type => "#{category}_set_angle"}
      = toolbox_number_value('ANGLE', 90)

    -# [▼]へ向ける
    %block{:type => "#{category}_point_towards_character"}

    -# マウスポインターへ向ける
    %block{:type => "#{category}_point_towards_mouse"}

    -# [▼]へ行く
    %block{:type => "#{category}_go_to_character"}

    -# マウスポインターへ行く
    %block{:type => "#{category}_go_to_mouse"}

    -# x座標を(　)ずつ変える
    %block{:type => "#{category}_change_x_by"}
      = toolbox_number_value('X', 10)

    -# x座標を(　)にする
    %block{:type => "#{category}_set_x"}
      = toolbox_number_value('X', 0)

    -# y座標を(　)ずつ変える
    %block{:type => "#{category}_change_y_by"}
      = toolbox_number_value('Y', 10)

    -# y座標を(　)にする
    %block{:type => "#{category}_set_y"}
      = toolbox_number_value('Y', 0)

    -# もし端に着いたら、跳ね返る
    %block{:type => "#{category}_turn_if_reach_wall"}

    -# 跳ね返る
    %block{:type => "#{category}_turn"}

    -# [▼水平(X)]方向に跳ね返る
    %block{:type => "#{category}_turn_xy"}

    -# 回転方法を[▼]にする
    %block{:type => "#{category}_set_rotation_style"}

  - category = 'looks'
  %category{:name => tt('.looks')}
    -# [　]と言う
    %block{:type => "#{category}_say"}
      = toolbox_text_value('TEXT', tt('.hello'))

    -# [　]と考える
    -#%block{:type => "#{category}_think"}
    -#  = toolbox_text_value('TEXT', 'ふーん')

    -# 表示する
    %block{:type => "#{category}_show"}

    -# 隠す
    %block{:type => "#{category}_hide"}

    -# 消滅する
    %block{:type => "#{category}_vanish"}

    -# 大きさを(　)％ずつ変える
    -#%block{:type => "#{category}_change_scale_by"}
    -#  = toolbox_number_value('SCALE', 10)

    -# 大きさを(　)％にする
    -#%block{:type => "#{category}_set_scale"}
    -#  = toolbox_number_value('SCALE', 100)

  - category = 'sound'
  %category{:name => tt('.sound')}
    -# [▼プリセット音声]の音を鳴らす
    %block{:type => "#{category}_play"}
      %value{:name => 'NAME'}
        %block{:type => "#{category}_preset_sounds"}

    -# すべての音を止める
    -#%block{:type => "#{category}_stop"}

  %category{name: tt('.data'), custom: 'VARIABLE'}

  - category = 'events'
  %category{:name => tt('.events')}
    -# まずは
    %block{:type => "#{category}_on_start"}

    -# キーボードの[▼キー]が[▼押された/押され続けている]とき
    %block{:type => "#{category}_on_key_push_or_down"}
      = toolbox_key_field
      = toolbox_pod_field

    -# キャラクターがクリックされたとき
    %block{:type => "#{category}_on_click"}

    -# [▼キャラクター]にぶつかったとき
    %block{:type => "#{category}_on_hit"}

  - category = 'control'
  %category{:name => tt('.control')}
    -# (　)秒待つ
    %block{:type => "#{category}_sleep"}
      = toolbox_number_value('SEC', 1)

    -# ほんの少し待つ
    %block{:type => "#{category}_await"}

    -# (　)回繰り返す
    %block{:type => "#{category}_times"}
      = toolbox_number_value('COUNT', 10)

    -# ずっと
    %block{:type => "#{category}_loop"}

    -# もし<　>なら
    %block{:type => "#{category}_if"}

    -# <　>まで待つ
    %block{:type => "#{category}_await_until"}

    -# 繰り返しから脱出する
    %block{:type => "#{category}_break"}

  - category = 'sensing'
  %category{:name => tt('.sensing')}
    -# 条件:[▼キャラクター]に触れた
    %block{:type => "#{category}_hit"}

    -# 条件:端に触れた
    %block{:type => "#{category}_reach_wall"}

    -# [　]と聞いて待つ
    -#%block{:type => "#{category}_ask"}
    -#  = toolbox_text_value('TEXT', 'あなたのお名前は？')

    -# 変数:答え
    -#%block{:type => "#{category}_answer"}

    -# 条件:キーボードの[▼キー]が[▼押された]
    %block{:type => "#{category}_input_key_push_or_down"}
      = toolbox_key_field
      = toolbox_pod_field

    -# 条件:マウスの[▼左ボタン]が[▼押された]
    %block{:type => "#{category}_input_mouse_push_or_down"}
      = toolbox_pod_field

    -# 変数:マウスのx座標
    %block{:type => "#{category}_input_mouse_pos_x"}

    -# 変数:マウスのy座標
    %block{:type => "#{category}_input_mouse_pos_y"}

    -# 変数:タイマー
    -#%block{:type => "#{category}_timer_count"}

    -# タイマーをリセット
    -#%block{:type => "#{category}_timer_reset"}

    -# 変数:[▼キャラクター]の[▼プロパティ]
    %block{:type => "#{category}_character_property"}

  - category = 'operators'
  %category{:name => tt('.operators')}
    -# 数値
    %block{:type => 'math_number'}
      %field{:name => 'NUM'}<
        0

    -# テキスト
    %block{:type => 'text'}
      %field{:name => 'TEXT'}<
        = tt('.text')

    -# 変数:(　) + (　)
    %block{:type => "#{category}_add"}

    -# 変数:(　) - (　)
    %block{:type => "#{category}_minus"}

    -# 変数:(　) * (　)
    %block{:type => "#{category}_multiply"}

    -# 変数:(　) / (　)
    %block{:type => "#{category}_divide"}

    -# 変数:(　)から(　)までの乱数
    %block{:type => "#{category}_rand"}
      = toolbox_number_value('A', 1)
      = toolbox_number_value('B', 10)

    -# 条件:(　) < (　)
    %block{:type => "#{category}_compare_lt"}

    -# 条件:(　) = (　)
    %block{:type => "#{category}_compare_eq"}

    -# 条件:(　) > (　)
    %block{:type => "#{category}_compare_gt"}

    -# 条件:<　> かつ <　>
    %block{:type => "#{category}_and"}

    -# 条件:<　> または <　>
    %block{:type => "#{category}_or"}

    -# 条件:<　> ではない
    %block{:type => "#{category}_negate"}

    -# 変数:(　)を(　)で割った余り
    %block{:type => "#{category}_modulo"}
      = toolbox_number_value('A', 5)
      = toolbox_number_value('B', 2)

    -# 変数:(　)を四捨五入
    %block{:type => "#{category}_round"}
      = toolbox_number_value('A', 0.5)

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/views/editor/_toolbox_smalrubot_s1.html.haml
%xml{:id => 'toolbox', :style => 'display: none'}
  %category{:name => tt('.motion')}
    - category = 'hardware'
    - subcategory = 'smalrubot_s1'
    %block{type: "#{category}_#{subcategory}_action"}
      %field{name: 'ACTION'}<
        forward

    %block{type: "#{category}_#{subcategory}_action_with_sec"}
      %field{name: 'ACTION'}<
        forward
      = toolbox_number_value('SEC', 0.5)

    %block{type: "#{category}_#{subcategory}_dc_motor_set_power_ratio"}
      = toolbox_number_value('SPEED', 100)

  - category = 'looks'
  %category{:name => tt('.looks')}
    %block{:type => "#{category}_say"}
      %value{name: 'TEXT'}
        - category = 'hardware'
        - subcategory = 'smalrubot_s1'
        %block{type: "#{category}_#{subcategory}_ir_photoreflector_value"}

    - category = 'hardware'
    - subcategory = 'smalrubot_s1'
    %block{type: "#{category}_#{subcategory}_led_turn_on_or_off"}
      %field{name: 'OOO'}<
        turn_on

  %category{:name => tt('.data'), :custom => 'VARIABLE'}

  - category = 'events'
  %category{:name => tt('.events')}
    -# まずは
    %block{:type => "#{category}_on_start"}

    -# キーボードの[▼キー]が[▼押された/押され続けている]とき
    %block{:type => "#{category}_on_key_push_or_down"}
      = toolbox_key_field
      = toolbox_pod_field

    -# キャラクターがクリックされたとき
    %block{:type => "#{category}_on_click"}

  - category = 'control'
  %category{:name => tt('.control')}
    -# (　)秒待つ
    %block{:type => "#{category}_sleep"}
      = toolbox_number_value('SEC', 1)

    -# ほんの少し待つ
    %block{:type => "#{category}_await"}

    -# (　)回繰り返す
    %block{:type => "#{category}_times"}
      = toolbox_number_value('COUNT', 10)

    -# ずっと
    %block{:type => "#{category}_loop"}

    -# もし<　>なら
    %block{:type => "#{category}_if"}

    -# もし<　>なら～でなければ
    %block{:type => "#{category}_if_else"}

    -# <　>まで待つ
    %block{:type => "#{category}_await_until"}

    -# <　>まで繰り返す
    %block{:type => "#{category}_until"}

    -# 繰り返しから脱出する
    %block{:type => "#{category}_break"}

    -# 次の繰り返しにジャンプする
    %block{:type => "#{category}_next"}

  - category = 'sensing'
  %category{:name => tt('.sensing')}
    -# 条件:キーボードの[▼キー]が[▼押された]
    %block{:type => "#{category}_input_key_push_or_down"}
      = toolbox_key_field
      = toolbox_pod_field

    -# 条件:マウスの[▼左ボタン]が[▼押された]
    %block{:type => "#{category}_input_mouse_push_or_down"}
      = toolbox_pod_field

    -# [　]と聞いて待つ
    -#%block{:type => "#{category}_ask"}
    -#  = toolbox_text_value('TEXT', 'あなたのお名前は？')

    -# 変数:答え
    -#%block{:type => "#{category}_answer"}

    -# 変数:タイマー
    -#%block{:type => "#{category}_timer_count"}

    -# タイマーをリセット
    -#%block{:type => "#{category}_timer_reset"}

    - category = 'hardware'
    - subcategory = 'smalrubot_s1'
    %block{type: "#{category}_#{subcategory}_ir_photoreflector_value"}
    %block{type: "#{category}_#{subcategory}_dc_motor_power_ratio"}

  - category = 'operators'
  %category{:name => tt('.operators')}
    -# 数値
    %block{:type => 'math_number'}
      %field{:name => 'NUM'}<
        0

    -# テキスト
    %block{:type => 'text'}
      %field{:name => 'TEXT'}<
        = tt('.text')

    -# 変数:(　) + (　)
    %block{:type => "#{category}_add"}

    -# 変数:(　) - (　)
    %block{:type => "#{category}_minus"}

    -# 変数:(　) * (　)
    %block{:type => "#{category}_multiply"}

    -# 変数:(　) / (　)
    %block{:type => "#{category}_divide"}

    -# 変数:(　)から(　)までの乱数
    %block{:type => "#{category}_rand"}
      = toolbox_number_value('A', 1)
      = toolbox_number_value('B', 10)

    -# 条件:(　) < (　)
    %block{:type => "#{category}_compare_lt"}

    -# 条件:(　) <= (　)
    %block{:type => "#{category}_compare_lte"}

    -# 条件:(　) = (　)
    %block{:type => "#{category}_compare_eq"}

    -# 条件:(　) >= (　)
    %block{:type => "#{category}_compare_gte"}

    -# 条件:(　) > (　)
    %block{:type => "#{category}_compare_gt"}

    -# 条件:<　> かつ <　>
    %block{:type => "#{category}_and"}

    -# 条件:<　> または <　>
    %block{:type => "#{category}_or"}

    -# 条件:<　> ではない
    %block{:type => "#{category}_negate"}

    -# 変数:(　)の(　)番目
    %block{:type => "#{category}_index_of"}
      = toolbox_text_value('A', tt('.world'))
      = toolbox_number_value('INDEX', 1)

    -# 変数:(　)の長さ
    %block{:type => "#{category}_length"}
      = toolbox_text_value('A', tt('.world'))

    -# 変数:(　)を(　)で割った余り
    %block{:type => "#{category}_modulo"}
      = toolbox_number_value('A', 5)
      = toolbox_number_value('B', 2)

    -# 変数:(　)を四捨五入
    %block{:type => "#{category}_round"}
      = toolbox_number_value('A', 0.5)

    -# 変数:(　)の[▼数学関数]
    %block{:type => "#{category}_math_method"}
      = toolbox_number_value('NUM', 9)
      %field{:name => 'METHOD'}<
        Math.sqrt(%num%)

    -# 条件:真
    %block{:type => "#{category}_true"}

    -# 条件:偽
    %block{:type => "#{category}_false"}

  - if !SmalrubyEditor::Config.enabled?('auto_init_hardware')
    %category{:name => tt('.etc')}
      - category = 'hardware'
      -# ハードウェアを準備する
      %block{:type => "#{category}_init_hardware"}

Ruby200_32/lib/ruby/gems/2.0.0/gems/smalruby-editor-0.2.4-x86-mingw32/app/views/editor/index.html.haml
.navbar{:id => "main-menu", :class => 'navbar-inverse'}
  .navbar-inner
    %ul.nav{:id => 'tabs'}
      %li.active
        %a#block-mode-button{:href => "#block-tab"}<
          %i.icon-folder-close
          =t('.block')
      %li
        %a#ruby-mode-button{:href => "#ruby-tab"}<
          %i.icon-pencil
          Ruby

    = form_tag(source_codes_load_path, id: "file-form", class: "navbar-form pull-right", method: "post", multipart: true) do
      %input#load-file{:type => 'file', :name => 'source_code[file]', :style => 'display: none'}
      %input#filename{:type => 'text', :class => 'span4', :placeholder => t('.msg_input_program_name')}
      = link_to '', source_codes_download_path, id: 'download-link', style: 'display: none', 'data-method' => 'delete'

      - if standalone?
        %button#run-button{:class => "btn btn-success"}<
          %i.icon-flag
          = t('.run')
      - else
        %button#download-button{:class => "btn btn-primary"}<
          %i.icon-download-alt
          = t('.download')

      - if raspberrypi?
        - if standalone?
          - load_id = 'load-local-button'
        - else
          - load_id = 'load-button'
        %button.btn{id: "#{load_id}", class: "btn btn-primary"}<
          %i.icon-folder-open
          = t('.load')
        - if standalone?
          %button#save-button.btn{class: "btn-primary"}<
            %i.icon-hdd
            = t('.save')
        %button#check-button.btn{class: "btn-primary"}<
          %i.icon-check
          = t('.check')
        %button#reset-button.btn{class: "btn-primary"}<
          %i.icon-off
          = t('.reset')
        - if standalone?
          - if session[:username]
            %button#signout-button.btn{class: "btn-primary"}<
              %i.icon-eject
              = t('.logout')
          - else
            %button#signout-button.btn{class: "btn-primary", style: "display: none"}<
              %i.icon-eject
              = t('.logout')

      - else
        .btn-group
          %a#submenu-button{:class => "dropdown-toggle btn btn-primary", :"data-toggle" => "dropdown", :href => "#"}
            %i.icon-reorder
          %ul#submenu.dropdown-menu{:class => "pull-right"}
            %li
              - if standalone?
                - load_id = 'load-local-button'
              - else
                - load_id = 'load-button'
              %a{:id => "#{load_id}"}
                %h4
                  %i.icon-folder-open
                  = t('.load')
            - if standalone?
              %li
                %a#save-button
                  %h4
                    %i.icon-hdd
                    = t('.save')
            %li
              %a#check-button
                %h4
                  %i.icon-check
                  = t('.check')
            %li
              %a#reset-button
                %h4
                  %i.icon-off
                  = t('.reset')
            - if standalone?
              %li
                - if session[:username]
                  %a#signout-button
                    %h4
                      %i.icon-eject
                      = t('.logout')
                - else
                  %a#signout-button{style: "display: none"}
                    %h4
                      %i.icon-eject
                      = t('.logout')

      - if standalone?
        - if session[:username]
          %button#signin-button{class: "btn btn-danger", style: "display: none"}<
            %i.icon-user
            = t('.login')
          %button#username-button{class: "btn btn-success"}<
            %i.icon-user
            %span#username-label<
              = session[:username]
        - else
          %button#signin-button{class: "btn btn-danger"}<
            %i.icon-user
            = t('.login')
          %button#username-button{class: "btn btn-success", style: "display: none"}<
            %i.icon-user
            %span#username-label

#messages

#modes-container{:class => 'tab-content'}
  #block-tab{:class => 'tab-pane active modes-tab-pane'}
    = render 'block_tab'

  #ruby-tab{:class => 'tab-pane modes-tab-pane'}
    #text-editor

= render 'signin_modal'
= render 'load_modal'
= render 'reset_modal'

- if session[:username]
  :javascript
    window.Smalruby.username = '#{h session[:username]}';

- if SmalrubyEditor::Config.features.is_a?(Array)
  :javascript
    window.Smalruby.Features = #{SmalrubyEditor::Config.features.to_json};